google_analytics: UA-119936887-1
theme: jekyll-theme-minimal
logo: images/jpanda.png
title: Jay Guru Panda
description: Computer Science B. Tech (Honors) + MS by Research at IIIT Hyderabad. Experienced in building and scaling computer vision and machine learning/deep learning systems.